name: Complex Workflow
on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{ github.repository_owner }}

    - name: Add local bin to path
      run: |
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Run frontend tests
      run: |
        pip install -r complex-workflow/requirements.txt
        pytest complex-workflow/backend --junit-xml=junit-backend.xml

    - name: Push test results to testspace
      run: |
          testspace "[backend]./junit-backend.xml{complex-workflow/backend}"
      working-directory: ${{env.working-directory}}
      if: always()

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{ github.repository_owner }}

    - name: Add local bin to path
      run: |
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Run frontend tests
      run: |
        pip install -r complex-workflow/requirements.txt
        pytest complex-workflow/frontend --junit-xml=junit-frontend.xml

    - name: Push test results to testspace
      run: |
          testspace "[frontend]./junit-frontend.xml{complex-workflow/frontend}"
      working-directory: ${{env.working-directory}}
      if: always()

  artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{ github.repository_owner }}

    - name: Add local bin to path
      run: |
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Run frontend tests
      run: |
        pip install -r complex-workflow/requirements.txt
        pytest --junit-xml=junit-frontend.xml

    - name: Push test results to testspace
      run: |
          testspace ./junit-frontend.xml @artifact-list.txt
      working-directory: ${{env.working-directory}}
      if: always()
